on:
  workflow_call:

jobs:
  start-request:
    runs-on: ubuntu-latest
    steps:
      - name: Init Dev Start Request Time
        run: |
          echo AWS_DEV_START_REQUEST=\"$(date +'%Y-%m-%d %H:%M:%S')\" > aws_dev_start_request.txt
          cat aws_dev_start_request.txt

      - name: Upload Dev Start Request File
        uses: actions/upload-artifact@v4
        with:
          name: aws-dev-start-request-artifact
          path: aws_dev_start_request.txt
