name: Irchad Dev Start Request

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: Application Name
        type: choice
        required: true
        default: 'maraqi'
        options:
        - maraqi
        - albaji
        - fitya
      lifetime:
        description: Dev Env Lifetime (Minutes)
        type: choice
        required: true
        default: '60'
        options:
        - 15
        - 60
        - 90
        - 120
        - 180

jobs:
  start-request:
    runs-on: ubuntu-latest
    steps:
      - name: Init Dev Start Request
        env:
          AWS_DEV_LIFETIME_REQUEST: ${{ inputs.lifetime }}
        run: |       
          echo AWS_DEV_START_REQUEST=\"$(date +'%Y-%m-%d %H:%M:%S')\" > aws_dev_start_request.txt
          echo AWS_DEV_LIFETIME_REQUEST=\"$AWS_DEV_LIFETIME_REQUEST\" >> aws_dev_start_request.txt         
          cat aws_dev_start_request.txt

      - name: Upload Dev Start Request File
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.app_name }}-dev-start-request-artifact
          path: aws_dev_start_request.txt
